apiVersion: v1
kind: Service
metadata:
  labels:
    app: "cookie-service"
  name: "cookie-service"
  namespace: "default"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: remoting
      port: 2552
      protocol: TCP
      targetPort: 2552
    - name: management
      port: 8558
      protocol: TCP
      targetPort: 8558
  selector:
    app: "cookie-app"
